// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gybixndluavyufbenwyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Yml4bmRsdWF2eXVmYmVud3l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMzEzMzYsImV4cCI6MjA1NjcwNzMzNn0.DFMaDOop81D57mbZuh0fK6q2DMoPuZhjdVoTESlb2GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);